#!/bin/bash
# Configure GPU passthrough for the Windows KVM VM
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=common.sh
source "$SCRIPT_DIR/common.sh"

usage() {
    cat <<EOF
Usage: $0 [options]

Configure VFIO GPU passthrough for $VM_NAME.

Options:
  --enable [SLOTS]   Enable passthrough (comma-separated PCI slots)
  --auto             Auto-detect the first discrete GPU (+ HDMI audio)
  --disable          Disable passthrough (QXL + SPICE only)
  --status           Show current GPU configuration
  -h, --help         Show this help

Examples:
  $0 --auto
  $0 --enable 01:00.0,01:00.1
  $0 --disable

After changing GPU settings, re-apply the VM definition:
  ./scripts/stop-vm.sh
  ./scripts/setup-vm.sh
EOF
}

check_iommu() {
    if ! dmesg 2>/dev/null | grep -qiE 'DMAR:.*enabled|AMD-Vi.*enabled'; then
        if [ ! -d /sys/kernel/iommu_groups ] || [ -z "$(ls -A /sys/kernel/iommu_groups 2>/dev/null)" ]; then
            echo "WARNING: IOMMU may not be enabled."
            echo "  Enable Intel VT-d / AMD-Vi in BIOS."
            echo "  Add to kernel cmdline: intel_iommu=on (or amd_iommu=on)"
            echo ""
        fi
    fi
}

check_vfio() {
    if ! modinfo vfio-pci &>/dev/null; then
        echo "ERROR: vfio-pci kernel module not available."
        exit 1
    fi
}

write_gpu_conf() {
    local passthrough="$1"
    local slots="$2"
    local auto="$3"

    cat > "$GPU_CONF" <<EOF
# Generated by setup-gpu.sh on $(date -Iseconds)
GPU_PASSTHROUGH=$passthrough
GPU_PCI_SLOTS=$slots
GPU_AUTO_DETECT=$auto
EOF
    echo "Wrote $GPU_CONF"
}

show_status() {
    if [ -f "$GPU_CONF" ]; then
        echo "=== GPU configuration ($GPU_CONF) ==="
        cat "$GPU_CONF"
        echo ""
    else
        echo "No gpu.conf found. Passthrough is disabled (QXL + SPICE)."
        echo "Copy scripts/gpu.conf.example to scripts/gpu.conf or run: $0 --auto"
        echo ""
    fi

    echo "=== Detected GPUs ==="
    "$SCRIPT_DIR/detect-gpu.sh" || true
}

enable_passthrough() {
    local slots="${1:-}"
    local auto=0

    check_iommu
    check_vfio

    if [ -z "$slots" ]; then
        slots=$("$SCRIPT_DIR/detect-gpu.sh" --pick)
        auto=1
    fi

    if [ -z "$slots" ]; then
        echo "ERROR: No GPU slots specified and auto-detect failed."
        exit 1
    fi

    # Accept comma- or space-separated slots; normalize to comma-separated.
    slots=$(echo "$slots" | tr -s '[:space:]' ',' | sed 's/,,*/,/g; s/^,//; s/,$//')

    local slot
    local IFS=','
    for slot in $slots; do
        slot="${slot//[[:space:]]/}"
        [ -n "$slot" ] || continue
        if [ ! -e "/sys/bus/pci/devices/0000:${slot}" ]; then
            echo "ERROR: PCI device not found: $slot"
            exit 1
        fi
    done

    write_gpu_conf 1 "$slots" "$auto"

    echo ""
    echo "GPU passthrough enabled for: $slots"
    echo ""
    echo "NVIDIA GPUs require the proprietary driver on the host to be unloaded."
    echo "If the host is using the GPU for display, passthrough may fail unless you"
    echo "use a dual-GPU setup (Intel iGPU for host, discrete GPU for VM)."
    echo ""
    echo "Re-apply VM definition:"
    echo "  ./scripts/stop-vm.sh && ./scripts/setup-vm.sh"
    echo ""
    echo "Inside Windows after install, install the GPU vendor driver (NVIDIA/AMD)."
}

disable_passthrough() {
    write_gpu_conf 0 "" 0
    echo "GPU passthrough disabled. VM will use QXL + SPICE."
    echo "Re-apply: ./scripts/stop-vm.sh && ./scripts/setup-vm.sh"
}

ACTION=""
SLOTS=""

while [ $# -gt 0 ]; do
    case "$1" in
        --enable)
            ACTION=enable
            shift
            if [ $# -gt 0 ] && [[ "$1" != --* ]]; then
                SLOTS="$1"
                shift
            fi
            ;;
        --auto)
            ACTION=enable
            SLOTS=""
            shift
            ;;
        --disable)
            ACTION=disable
            shift
            ;;
        --status)
            ACTION=status
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

case "${ACTION:-status}" in
    enable) enable_passthrough "$SLOTS" ;;
    disable) disable_passthrough ;;
    status) show_status ;;
    *) show_status ;;
esac